name: Build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    #if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Gradle
        id: cache-gradle
        uses: actions/cache@v4.2.2
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle

      - uses: actions/checkout@v4.2.2

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build -x test --warning-mode all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
